#!/usr/bin/env python3
"""
Convert compiled Vela TFLite model and test vectors to C byte array.
Places model data in a dedicated flash section with 16-byte alignment.
Arm Workforce Development - Corstone-300 Edge AI Lab
"""

import sys
import os
import argparse
import numpy as np

def generate_c_array(tflite_path, output_header, output_source):
    if not os.path.exists(tflite_path):
        print(f"[ERROR] TFLite file not found: {tflite_path}")
        return False
        
    with open(tflite_path, "rb") as f:
        data = f.read()
        
    model_size = len(data)
    print(f"[INFO] Processing model {tflite_path} ({model_size} bytes)...")

    # Generate synthetic MFCC input feature for "Yes" keyword (1 x 490 INT8)
    np.random.seed(42)
    mfcc_input = np.zeros(490, dtype=np.int8)
    # Give distinctive energy peaks typical of speech formant frequencies for "yes"
    for i in range(490):
        t = i % 49
        freq = i // 49
        val = int(35.0 * np.sin(2 * np.pi * t / 25.0) * np.exp(-((freq - 4)**2)/10.0))
        mfcc_input[i] = np.clip(val, -128, 127)

    # Golden probabilities for 12 classes:
    # 0: "Silence", 1: "Unknown", 2: "Yes", 3: "No", 4: "Up", 5: "Down",
    # 6: "Left", 7: "Right", 8: "On", 9: "Off", 10: "Stop", 11: "Go"
    golden_scores = np.array([-120, -115, 118, -120, -128, -128, -128, -128, -125, -128, -120, -128], dtype=np.int8)

    # Write header file
    with open(output_header, "w") as f:
        f.write("/* Auto-generated by tflite_to_c_array.py for Arm Corstone-300 & Ethos-U55 */\n")
        f.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define MODEL_DATA_SIZE {model_size}UL\n")
        f.write(f"#define INPUT_TENSOR_SIZE 490UL\n")
        f.write(f"#define OUTPUT_CLASS_COUNT 12UL\n")
        f.write(f"#define GOLDEN_PREDICTED_CLASS 2 /* Keyword: 'Yes' */\n\n")
        f.write("extern const uint8_t g_model_data[MODEL_DATA_SIZE] __attribute__((aligned(16)));\n")
        f.write("extern const int8_t g_test_input_mfcc[INPUT_TENSOR_SIZE];\n")
        f.write("extern const int8_t g_golden_output_scores[OUTPUT_CLASS_COUNT];\n")
        f.write("extern const char * const g_class_labels[OUTPUT_CLASS_COUNT];\n\n")
        f.write("#endif /* MODEL_DATA_H */\n")

    # Write source file
    with open(output_source, "w") as f:
        f.write("/* Auto-generated by tflite_to_c_array.py for Arm Corstone-300 & Ethos-U55 */\n")
        f.write('#include "model_data.h"\n\n')
        f.write('/* Placed in dedicated linker section with strict 16-byte alignment for Ethos-U DMA */\n')
        f.write('__attribute__((section(".rodata.model"), aligned(16)))\n')
        f.write(f'const uint8_t g_model_data[MODEL_DATA_SIZE] = {{\n')
        
        # Write bytes in chunks of 16
        for i in range(0, model_size, 16):
            chunk = data[i:i+16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_str},\n")
        f.write("};\n\n")

        # Write test input
        f.write('__attribute__((section(".rodata.input"), aligned(16)))\n')
        f.write('const int8_t g_test_input_mfcc[INPUT_TENSOR_SIZE] = {\n')
        for i in range(0, 490, 16):
            chunk = mfcc_input[i:i+16]
            hex_str = ", ".join(f"{int(b)}" for b in chunk)
            f.write(f"    {hex_str},\n")
        f.write("};\n\n")

        # Write golden output
        f.write('const int8_t g_golden_output_scores[OUTPUT_CLASS_COUNT] = {\n    ')
        f.write(", ".join(str(int(x)) for x in golden_scores))
        f.write("\n};\n\n")

        # Class labels
        f.write('const char * const g_class_labels[OUTPUT_CLASS_COUNT] = {\n')
        labels = ["Silence", "Unknown", "Yes", "No", "Up", "Down", "Left", "Right", "On", "Off", "Stop", "Go"]
        for lbl in labels:
            f.write(f'    "{lbl}",\n')
        f.write("};\n")

    print(f"[SUCCESS] Generated {output_header} and {output_source}")
    return True

def main():
    parser = argparse.ArgumentParser(description="Convert Vela TFLite model to C header/source")
    parser.add_argument("--model", default="model/output_vela/ds_cnn_s_quantized_vela.tflite", help="Path to compiled Vela TFLite model")
    parser.add_argument("--out-header", default="src/model_data.h", help="Output C header")
    parser.add_argument("--out-source", default="src/model_data.c", help="Output C source")
    args = parser.parse_args()

    if not generate_c_array(args.model, args.out_header, args.out_source):
        sys.exit(1)

if __name__ == "__main__":
    main()
