/* Auto-generated by tflite_to_c_array.py for Arm Corstone-300 & Ethos-U55 */
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

#define MODEL_DATA_SIZE 35920UL
#define INPUT_TENSOR_SIZE 490UL
#define OUTPUT_CLASS_COUNT 12UL
#define GOLDEN_PREDICTED_CLASS 2 /* Keyword: 'Yes' */

extern const uint8_t g_model_data[MODEL_DATA_SIZE] __attribute__((aligned(16)));
extern const int8_t g_test_input_mfcc[INPUT_TENSOR_SIZE];
extern const int8_t g_golden_output_scores[OUTPUT_CLASS_COUNT];
extern const char * const g_class_labels[OUTPUT_CLASS_COUNT];

#endif /* MODEL_DATA_H */
